package com.khandelwal.creational.designpattern.prototype;

import org.junit.Test;

import com.khandelwal.creational.designpattern.prototype.File;
import com.khandelwal.creational.designpattern.prototype.PrototypeFactory;
import com.khandelwal.creational.designpattern.prototype.TextFile;

import static org.junit.Assert.*;

/**
 * The class <code>PrototypeJunitTest</code> contains tests for the class
 * {@link <code>PrototypeJunit</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 1/31/16 8:27 PM
 *
 * @author Abhishek
 *
 * @version $Revision$
 */
public class PrototypeJunit {

	@Test
	public void prototypeDesignPatternTestCase()
			throws CloneNotSupportedException {

		File textFile = new TextFile();
		File clonedFile = PrototypeFactory.getClone(textFile);

		assertNotEquals(System.identityHashCode(textFile),
				System.identityHashCode(clonedFile));
	}
}

/*
 * $CPS$ This comment was generated by CodePro. Do not edit it. patternId =
 * com.instantiations.assist.eclipse.pattern.testCasePattern strategyId =
 * com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = assertTrue = false callTestMethod = true createMain =
 * false createSetUp = false createTearDown = false createTestFixture = false
 * createTestStubs = false methods = package =
 * com.khandelwal.designpattern.prototype package.sourceFolder =
 * designpattern/src/test/java superclassType = junit.framework.TestCase
 * testCase = PrototypeJunitTest testClassType =
 * com.khandelwal.designpattern.prototype.PrototypeJunit
 */